#!/usr/bin/env python3
"""
inject_config.py — run by GitHub Actions during deployment.

Reads CV_API_KEY, CV_PROVIDER, CV_MODEL from environment variables
(populated from GitHub Secrets/Variables) and writes a safe js/config.js.

Uses json.dumps() so special characters in the key ($, ", \, etc.)
are always correctly escaped as JavaScript string literals.
"""
import os
import json

api_key  = os.environ.get("CV_API_KEY",  "")
provider = os.environ.get("CV_PROVIDER", "") or "claude"
model    = os.environ.get("CV_MODEL",    "") or "claude-sonnet-4-5-20250929"

lines = [
    "// Auto-generated by GitHub Actions -- do not edit manually.",
    "// Regenerated on every push to main.",
    "// To update: change the CLEARVOICE_API_KEY secret in repository settings.",
    "window.CV_CONFIG = {",
    "  apiKey  : " + json.dumps(api_key)  + ",",
    "  provider: " + json.dumps(provider) + ",",
    "  model   : " + json.dumps(model)    + ",",
    "};",
    "",
]

with open("js/config.js", "w") as f:
    f.write("\n".join(lines))

if api_key:
    print("API key injected into js/config.js")
else:
    print("No CLEARVOICE_API_KEY secret found -- deploying without key (users configure manually).")
